### ISSUE TITLE
Support Imagemagick binaries as well as imagick-library

### ISSUE THREAD

**Issue by heiglandreas** [imanee/imanee#22]
On some environments the imagick-library just isn't available but the imagemagick binaries are. Is there a way to support those as well for the library?

**Comment by erikaheidi** [comment]
hi @heiglandreas ! You mean, like, calling imagemagick on system? To be honest, I am not sure if it's a viable option, but it would be certainly a good thing to have. I will keep this in mind for the future. Thanks!

**Comment by heiglandreas** [comment]
hi @erikaheidi. Jepp. Like via an 'exec' call or 'passthru'. I can have a look at that later ehen you think it is an option. Any hints on where to look?

**Comment by erikaheidi** [comment]
hey @heiglandreas :) Well, I believe we could have adapters to work in a lower layer, so the native Imagemagick wrapper could replace the Imagick API for use with the Image class. It sounds like an interesting idea, probably a lot of work but I think it's doable.

**Comment by heiglandreas** [comment]
I'll have a look at it in the next days :smile:

**Comment by erikaheidi** [comment]
Gonna close this one, but if you get anything done ping me :) I'm currently working on a refactoring that will make it easier for supporting multiple Image providers.
