### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by tmblog** [imanee/imanee#24]
Would it be possible to add image compression?

**Comment by erikaheidi** [comment]
Hi @tmblog! Currently we use compression for JPG only, by default when a jpg file is written with the Imanee::write method. A smaller value gives you a lesser quality and smaller size. Do you have something else in mind? If you can elaborate a bit more I can try to help :)

In any case, if you need to do more advanced stuff you can get the Imagick object from Imanee with the method Imanee::getIMResource.
