### ISSUE TITLE
Write tests to cover GDResource

### ISSUE THREAD

**Issue by erikaheidi** [imanee/imanee#33]
Write tests for the class ``Imanee\ImageResource\GDResource``

**Comment by DragonBe** [comment]
Feeling great for testing tonight, so let's do this!

**Comment by erikaheidi** [comment]
YAY! :dancer:

**Comment by DragonBe** [comment]
issue #33: load(): first condition breakout tested
![imanee-33-load-first-condition-tested](https://cloud.githubusercontent.com/assets/282825/8361751/1290eea6-1b75-11e5-8706-e9336d0e986a.png)

**Comment by erikaheidi** [comment]
:+1: merged!
