### ISSUE TITLE
Write tests to cover GDPixel

### ISSUE THREAD

**Issue by erikaheidi** [imanee/imanee#34]
Write tests for the class ``Imanee\ImageResource\GDPixel``

**Comment by robth82** [comment]
I'm want to going work on this item!

**Comment by erikaheidi** [comment]
:+1: great!

**Comment by sminnee** [comment]
oops i started on this too ;-)

**Comment by sminnee** [comment]
I started on some tests, here is another one to add.


    /**
     * Check that colours can be created from appropriate color strings
     * @dataProvider colorTestValues
     */
	public function testCreateGDPixelByColorString($hexColor, $r, $g, $b)
    {
    	$gdPixel = new GDPixel($hexColor);
    	$this->assertEquals($r, $gdPixel->channelR, 'red value incorrect for ' . $hexColor);
    	$this->assertEquals($g, $gdPixel->channelG, 'green value incorrect for ' . $hexColor);
    	$this->assertEquals($b, $gdPixel->channelB, 'blue value incorrect for ' . $hexColor);
    }

    public function colorTestValues() {
    	return array(
    		array('#000000', 0, 0, 0),
    		array('000000', 0, 0, 0),
    		array('#FFFFFF', 255, 255, 255),
    		array('FFFFFF', 255, 255, 255),
    		array('#FF0000', 255, 0, 0),
    		array('#008000', 0, 128, 0),
    		array('#00000F', 0, 0, 15),

    		array('black', 0, 0, 0),
    		array('white', 255, 255, 255),
    	);
    }

**Comment by erikaheidi** [comment]
Fixed on #49
