### ISSUE TITLE
Create a new built-in filter

### ISSUE THREAD

**Issue by erikaheidi** [imanee/imanee#38]
Create a new Filter to be included with the default built-in filters. 

To be part of the built-in filters, a filter must be implemented for both Imagick and GD resources.

Check the documentation for more info: http://docs.imanee.io/en/latest/customFilter.html

**Comment by tiemevanveen** [comment]
I'll start on a blur filter!

**Comment by erikaheidi** [comment]
:+1:

**Comment by erikaheidi** [comment]
Done on #45 :clap:
