### ISSUE TITLE
Use Coveralls to see how developed tests are

### ISSUE THREAD

**Issue by Lewiscowles1986** [imanee/imanee#54]
Hi, this is just a suggestion, but have you considered using coveralls to demonstrate how many lines of the code are covered by the tests?

**Comment by erikaheidi** [comment]
Hi @Lewiscowles1986 ! That would be a great improvement. I can try to implement it, but if you want to do it that would be amazing.

Thank you!

**Comment by Lewiscowles1986** [comment]
I Stated working on it, I will get back to it soon

**Comment by Lewiscowles1986** [comment]
Steps to sign up to coveralls.io

1. visit coveralls.io
2. Sign up with GitHub (It's Free)
3. Click on Repo's
4. Click Add Repo's
5. Select imanee (turn on, it will go green, very similar to travis-ci repo enabling)
6. Merge the pull request ;)

**Comment by erikaheidi** [comment]
@Lewiscowles1986 awesome, doing this now :)

**Comment by Lewiscowles1986** [comment]
done :+1: thanks so much for assistance @erikaheidi and all involved! :smile_cat:
