### ISSUE TITLE
Get encoded image $resource or string

### ISSUE THREAD

**Issue by adaojunior** [imanee/imanee#57]
Is there a way to get the image resource or string ?
I want to create a thumbnail but I do not want to save it on disk before I can upload  to amazon's S3 through Flysystem.
I tried imanee and [intervention](http://image.intervention.io/) and I got that functionality by using intervention's method  [encode](http://image.intervention.io/api/encode).

**Comment by beryllium** [comment]
The $imanee->output() method has this description: "Output the current image resource as a string."

Sounds like what you want.

**Comment by erikaheidi** [comment]
the output method should return it as string, but there's a bug reported on #58 with GD - we will have this fixed ASAP

It works as expected with Imagick. Notice that the GD port is a newer implementation, so we are still fixing some bugs.
