### ISSUE TITLE
GD issue with output

### ISSUE THREAD

**Issue by mikeSimonson** [imanee/imanee#58]
The output() function is supposed to return the content of the image as a string.
https://github.com/imanee/imanee/blob/master/src/Imanee.php#L266.
As it's doing for the imagick driver.

The fix right now looks like something like this
```
ob_start();
imagejpeg($this->getResource(), null, 90);
$imageBlob = ob_get_contents();
ob_end_clean();
return $imageBlob
```

Should I make a pull request ?

**Comment by erikaheidi** [comment]
Oh, that passed completely unnoticed to me. Yes please, I don't think there's another way to do it... Can you please send a PR?

Thank you @mikeSimonson !
