### ISSUE TITLE
image rotation ?

### ISSUE THREAD

**Issue by mikeSimonson** [imanee/imanee#62]
I am wondering if @erikaheidi is interested into having the possibility to rotate images ?
And if so, does implementing a new interface for the resources like ImageRotation would make sense ?

**Comment by erikaheidi** [comment]
Well, actually... the rotate method already exists :D It's probably not in the demos, but it's there, and it's part of the default image resource interface.

``Imanee rotate($degrees = 90.00, $background = 'transparent')``

**Comment by mikeSimonson** [comment]
Wow don't know how I missed that?
